# Generated by Django 4.2.1 on 2023-06-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('lat', models.FloatField(unique=True, verbose_name='Широта')),
                ('lon', models.FloatField(unique=True, verbose_name='Долгота')),
                ('request_dt', models.DateTimeField(unique=True, verbose_name='Дата и время запроса')),
            ],
            options={
                'verbose_name': 'местоположение',
                'verbose_name_plural': 'местоположения',
            },
        ),
    ]
