# Generated by Django 4.2.1 on 2023-06-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationapp', '0006_alter_location_lat_alter_location_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=100, unique=True, verbose_name='Адрес'),
        ),
    ]
