# Generated by Django 4.2.1 on 2023-07-20 16:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('locationapp', '0008_auto_20230626_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='request_dt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время запроса'),
        ),
    ]
