# Generated by Django 4.2.1 on 2023-06-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_order_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(0, 'Необработанный'), (1, 'В сборке'), (2, 'В доставке'), (3, 'Выполнен')], db_index=True, default='raw', max_length=30, verbose_name='Статус заказа'),
        ),
    ]
