# Generated by Django 4.2.1 on 2023-06-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Необработанный'), (1, 'В сборке'), (2, 'В доставке'), (3, 'Выполнен')], db_index=True, default=0, verbose_name='Статус заказа'),
        ),
    ]
