# Generated by Django 4.2.1 on 2023-07-20 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0057_alter_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество'),
        ),
    ]
